version: 2
snapshot:
  widths:
    - 375
    - 1280
  minHeight: 1024
static:
  cleanUrls: false
discovery:
  allowedHostnames:
    - unpkg.com
    - ga.jspm.io
  networkIdleTimeout: 500
upload:
  stripExtensions: false
