# This workflow will validate the title of a PR to ensure it meets conventional commit standards
name: Validate conventional commit syntax

on:
  pull_request:
    types: [opened, edited, labeled, auto_merge_enabled]
  pull_request_review:
    types: [submitted]

env:
  TOKEN: "${{ secrets.GITHUB_TOKEN }}"

# Separate jobs can run concurrently
jobs:
  cc-format:
    name: Validate conventional commit format for title
    runs-on: ubuntu-latest

    steps:
      - name: Validate conventional commit format for title
        id: cc-format
        uses: aslafy-z/conventional-pr-title-action@v2.2.0
        continue-on-error: true
        with:
          success-state: Title follows the conventional commit format.
          failure-state: Please update the title to use conventional commit format.
          context-name: conventional-pr-title
          preset: conventional-changelog-angular@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
