# This workflow will automatically move cards in the project
# board to reflect that status of a PR.
name: Move PR cards on project board

on:
  pull_request:
    types:
      - opened
      - closed
      - labeled
      - unlabeled
      - converted_to_draft
      - ready_for_review
      - review_requested

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PROJECT_URL: https://github.com/patternfly/patternfly-elements/projects/5

jobs:
  project_board:
    name: Move cards in the project board according to label
    runs-on: ubuntu-latest
    if: contains(github.event.*.state, 'open')
    steps:
      - name: Assign new issues to project board
        uses: takanabe/github-actions-automate-projects@v0.0.1
        if: |
          github.event.action == 'opened' ||
          github.event.action == 'converted_to_draft' ||
          contains(github.event.*.labels.*.name, 'work in progress')
        env:
          GITHUB_PROJECT_COLUMN_NAME: In progress
      - name: Move to testing
        uses: takanabe/github-actions-automate-projects@v0.0.1
        if: |
          github.event.action == 'ready_for_review' ||
          contains(github.event.*.labels.*.name, 'ready: browser testing') ||
          contains(github.event.*.labels.*.name, 'ready: branch testing')
        env:
          GITHUB_PROJECT_COLUMN_NAME: "Ready: branch & browser testing"
      - name: Ready for code review
        uses: takanabe/github-actions-automate-projects@v0.0.1
        if: |
          github.event.action == 'review_requested' ||
          contains(github.event.*.labels.*.name, 'ready: code review') ||
          contains(github.event.*.labels.*.name, 'ready: design review')
        env:
          GITHUB_PROJECT_COLUMN_NAME: "Ready: code & design review"
      - name: Ready to merge
        uses: takanabe/github-actions-automate-projects@v0.0.1
        if: |
          (
            github.event.review.state == 'approved' &&
            !contains(github.event.*.labels.*.name, 'ready: design review') &&
            !contains(github.event.*.labels.*.name, 'ready: branch testing') &&
            !contains(github.event.*.labels.*.name, 'ready: browser testing')
          ) ||
          contains(github.event.*.labels.*.name, 'ready for merge')
        env:
          GITHUB_PROJECT_COLUMN_NAME: Approved
      - name: Completed
        uses: takanabe/github-actions-automate-projects@v0.0.1
        if: github.event.action == 'closed'
        env:
          GITHUB_PROJECT_COLUMN_NAME: Done
